# Generated by Django 5.0.3 on 2024-04-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkitem',
            options={'verbose_name': 'drink item'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'food item'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.drinkitem'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_placed', to='Home.table'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.fooditem'),
        ),
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_associated', to='Home.order'),
        ),
        migrations.CreateModel(
            name='GrubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.TextField()),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('fillings', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
