# Generated by Django 5.0.3 on 2024-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_category_default_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(default='The Pronto, Ilorin', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('ticket_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
