# Generated by Django 5.0.3 on 2024-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_event_remove_menuitem_image_url_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
