# Generated by Django 5.0.3 on 2024-06-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_category_default_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name_plural': 'Events'},
        ),
    ]
