# Generated by Django 5.0.3 on 2024-06-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_event_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
