# Generated by Django 5.0.3 on 2024-06-05 14:48

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
