# Generated by Django 5.0.3 on 2024-06-06 12:59

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_category_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_image',
            field=models.ImageField(blank=True, null=True, storage=Home.models.CustomStaticFileStorage(), upload_to='Static/images/'),
        ),
    ]
