# Generated by Django 5.0.3 on 2024-06-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_reservation_email_table_is_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
    ]
